FROM eclipse-temurin:21-jdk

RUN apt-get update && \
    apt-get install -y maven && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

WORKDIR /app

EXPOSE 8090

# Em desenvolvimento, usa spring-boot:run que suporta hot reload com devtools
CMD ["mvn", "spring-boot:run", "-Dspring-boot.run.jvmArguments=-Dspring.devtools.restart.enabled=true"]
