spring.datasource.url=jdbc:postgresql://postgres:5432/asteracomm

spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.username=asteracomm
spring.datasource.password=asteracomm

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=validate

spring.flyway.baseline-on-migrate=true
spring.flyway.baseline-version=1

asterisk.hostname=host.docker.internal
asterisk.port=5038
asterisk.username=admin
asterisk.password=admin
asterisk.dialplan.generated-path=/dialplan-generated

super.user.username=admin@asteracomm.com
super.user.password=admin123
super.user.name=AsteracommAdmin


# Desativa cache do Thymeleaf (essencial para reload de HTML)
spring.thymeleaf.cache=false
spring.thymeleaf.cache=false
spring.web.resources.cache.period=0
spring.web.resources.chain.cache=false

# LiveReload: alterações em templates/static só disparam refresh no browser (sem restart)
spring.devtools.livereload.enabled=true
spring.devtools.restart.exclude=templates/**,static/**
spring.devtools.restart.enabled=true

# Trigger file: DevTools só age quando este arquivo é tocado (necessário no Docker)
spring.devtools.restart.trigger-file=.reload-trigger

