package com.dionialves.AsteraComm.asterisk.dialplan;

import com.dionialves.AsteraComm.asterisk.provisioning.AmiService;
import com.dionialves.AsteraComm.trunk.Trunk;
import com.dionialves.AsteraComm.trunk.TrunkRepository;
import lombok.RequiredArgsConstructor;
import lombok.extern.slf4j.Slf4j;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.boot.context.event.ApplicationReadyEvent;
import org.springframework.context.event.EventListener;
import org.springframework.stereotype.Service;

import java.io.IOException;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.StandardOpenOption;
import java.time.LocalDateTime;
import java.util.List;

@Slf4j
@Service
@RequiredArgsConstructor
public class DialplanGeneratorService {

    private final TrunkRepository trunkRepository;
    private final AmiService amiService;

    @Value("${asterisk.dialplan.generated-path:/dialplan-generated}")
    private String generatedPath;

    @EventListener(ApplicationReadyEvent.class)
    public void onApplicationReady() {
        try {
            generateAndReload();
        } catch (Exception e) {
            log.error("Falha ao gerar extensions_trunks.conf na inicialização: {}", e.getMessage());
        }
    }

    public void generateAndReload() {
        generateTrunkContexts();
        amiService.sendCommand("dialplan reload");
    }

    public void generateTrunkContexts() {
        List<Trunk> trunks = trunkRepository.findAll();
        String content = buildFileContent(trunks);

        Path filePath = Path.of(generatedPath, "extensions_trunks.conf");
        try {
            Files.writeString(filePath, content, StandardCharsets.UTF_8,
                    StandardOpenOption.CREATE, StandardOpenOption.TRUNCATE_EXISTING);
            log.info("extensions_trunks.conf gerado com {} tronco(s) em {}", trunks.size(), filePath);
        } catch (IOException e) {
            throw new RuntimeException(
                    "Falha ao gravar extensions_trunks.conf em " + generatedPath + ": " + e.getMessage(), e);
        }
    }

    private String buildFileContent(List<Trunk> trunks) {
        StringBuilder sb = new StringBuilder();
        sb.append("; AUTO-GENERATED by AsteraComm — NÃO EDITE MANUALMENTE\n");
        sb.append("; Gerado em: ").append(LocalDateTime.now()).append("\n");

        for (Trunk trunk : trunks) {
            sb.append("\n[internal-").append(trunk.getName()).append("]\n");
            sb.append("switch => Realtime/@\n");
            sb.append("\n[pstn-").append(trunk.getName()).append("]\n");
            sb.append("switch => Realtime/@\n");
        }

        return sb.toString();
    }
}
