package com.dionialves.AsteraComm.asterisk.dialplan;

import com.dionialves.AsteraComm.asterisk.provisioning.AmiService;
import com.dionialves.AsteraComm.trunk.Trunk;
import com.dionialves.AsteraComm.trunk.TrunkRepository;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.extension.ExtendWith;
import org.junit.jupiter.api.io.TempDir;
import org.mockito.InjectMocks;
import org.mockito.Mock;
import org.mockito.junit.jupiter.MockitoExtension;
import org.springframework.test.util.ReflectionTestUtils;

import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.List;

import static org.assertj.core.api.Assertions.assertThat;
import static org.assertj.core.api.Assertions.assertThatThrownBy;
import static org.mockito.Mockito.verify;
import static org.mockito.Mockito.when;

@ExtendWith(MockitoExtension.class)
class DialplanGeneratorServiceTest {

    @Mock
    private TrunkRepository trunkRepository;

    @Mock
    private AmiService amiService;

    @InjectMocks
    private DialplanGeneratorService dialplanGeneratorService;

    @TempDir
    Path tempDir;

    @BeforeEach
    void setUp() {
        ReflectionTestUtils.setField(dialplanGeneratorService, "generatedPath", tempDir.toString());
    }

    @Test
    void generateTrunkContexts_withNoTrunks_shouldWriteHeaderOnly() throws IOException {
        when(trunkRepository.findAll()).thenReturn(List.of());

        dialplanGeneratorService.generateTrunkContexts();

        String content = Files.readString(tempDir.resolve("extensions_trunks.conf"));
        assertThat(content).contains("; AUTO-GENERATED by AsteraComm");
        assertThat(content).doesNotContain("[internal-");
        assertThat(content).doesNotContain("[pstn-");
    }

    @Test
    void generateTrunkContexts_withOneTrunk_shouldWriteBothContextStubs() throws IOException {
        Trunk trunk = new Trunk();
        trunk.setName("vivo");
        when(trunkRepository.findAll()).thenReturn(List.of(trunk));

        dialplanGeneratorService.generateTrunkContexts();

        String content = Files.readString(tempDir.resolve("extensions_trunks.conf"));
        assertThat(content).containsOnlyOnce("[internal-vivo]");
        assertThat(content).containsOnlyOnce("[pstn-vivo]");
        assertThat(content).contains("switch => Realtime/@");
    }

    @Test
    void generateTrunkContexts_withMultipleTrunks_shouldWriteAllContextsWithoutDuplicates() throws IOException {
        Trunk t1 = new Trunk(); t1.setName("claro");
        Trunk t2 = new Trunk(); t2.setName("vivo");
        Trunk t3 = new Trunk(); t3.setName("tim");
        when(trunkRepository.findAll()).thenReturn(List.of(t1, t2, t3));

        dialplanGeneratorService.generateTrunkContexts();

        String content = Files.readString(tempDir.resolve("extensions_trunks.conf"));
        assertThat(content).containsOnlyOnce("[internal-claro]");
        assertThat(content).containsOnlyOnce("[pstn-claro]");
        assertThat(content).containsOnlyOnce("[internal-vivo]");
        assertThat(content).containsOnlyOnce("[pstn-vivo]");
        assertThat(content).containsOnlyOnce("[internal-tim]");
        assertThat(content).containsOnlyOnce("[pstn-tim]");
    }

    @Test
    void generateAndReload_shouldCallDialplanReload() {
        when(trunkRepository.findAll()).thenReturn(List.of());

        dialplanGeneratorService.generateAndReload();

        verify(amiService).sendCommand("dialplan reload");
    }

    @Test
    void generateTrunkContexts_whenDirectoryNotWritable_shouldThrowDescriptiveException() {
        ReflectionTestUtils.setField(dialplanGeneratorService, "generatedPath", "/nonexistent/path/that/does/not/exist");
        when(trunkRepository.findAll()).thenReturn(List.of());

        assertThatThrownBy(() -> dialplanGeneratorService.generateTrunkContexts())
                .isInstanceOf(RuntimeException.class)
                .hasMessageContaining("/nonexistent/path/that/does/not/exist");
    }
}
